@startuml DiagClassesClients

skinparam classAttributeIconSize 0
skinparam class {
    BackgroundColor White
    BorderColor #000
}


package Entites {
    Client "1" --> "*" Adresse

    class Client {
        + ctor(p_clientId : Guid, p_nom : string, p_prenom : string, p_adresses : IEnumerable<Adresse>)
        + Guid ClientId <<get>> <<private set>>
        + string Nom <<get>> <<private set>>
        + string Prenom <<get>> <<private set>>
        + List<Adresse> Adresses <<get>> <<private set>>
        + AjouterModifierAdresse(p_adresse : Adresse)
    }

    class Adresse {
        + Guid AdresseId <<get>> <<private set>>
        + NumeroCivique : string <<get>> <<set>>
        + InformationComplementaire : string <<get>> <<set>>
        + Odonyme : string <<get>> <<set>>
        + TypeVoie : string <<get>> <<set>>
        + CodePostal : string <<get>> <<set>>
        + NomMunicipalite : string <<get>> <<set>>
        + Etat : string <<get>> <<set>>
        + Pays : string  <<get>> <<set>>
    }

    interface IDepotClients {
        + AjouterClient(p_client : Client)
        + ListerClients() : List<Client>
        + RechercherClient(p_clientId : Guid)
        + ModifierClient(p_client : Client)
    }
}

package CoucheAccesDonnees.JSON {
    IDepotClients <|.. DepotClientsJSON
    ClientJSONDTO "1" --> "*" AdresseJSONDTO

    class ClientJSONDTO {
        + Guid ClientId <<get>> <<private set>>
        + string Nom <<get>> <<private set>>
        + string Prenom <<get>> <<private set>>
        + List<Adresse> Adresses <<get>> <<private set>>
    }

    class AdresseJSONDTO {
        + Guid AdresseId <<get>> <<private set>>
        + NumeroCivique : string <<get>> <<set>>
        + InformationComplementaire : string <<get>> <<set>>
        + Odonyme : string <<get>> <<set>>
        + TypeVoie : string <<get>> <<set>>
        + CodePostal : string <<get>> <<set>>
        + NomMunicipalite : string <<get>> <<set>>
        + Etat : string <<get>> <<set>>
        + Pays : string  <<get>> <<set>>
    }

    class DepotClientsJSON {
        + AjouterClient(p_client : Client)
        + ListerClients() : List<Client>
        + RechercherClient(p_clientId : Guid)
        + ModifierClient(p_client : Client)
    }
}

package CoucheAccesDonnees.XML {
    IDepotClients <|.. DepotClientsXML
    ClientXMLDTO "1" --> "*" AdresseXMLDTO

    class ClientXMLDTO {
        + Guid ClientId <<get>> <<private set>>
        + string Nom <<get>> <<private set>>
        + string Prenom <<get>> <<private set>>
        + List<Adresse> Adresses <<get>> <<private set>>
    }

    class DepotClientsXML {
        + AjouterClient(p_client : Client)
        + ListerClients() : List<Client>
        + RechercherClient(p_clientId : Guid)
        + ModifierClient(p_client : Client)
    }

    class AdresseXMLDTO {
        + Guid AdresseId <<get>> <<private set>>
        + NumeroCivique : string <<get>> <<set>>
        + InformationComplementaire : string <<get>> <<set>>
        + Odonyme : string <<get>> <<set>>
        + TypeVoie : string <<get>> <<set>>
        + CodePostal : string <<get>> <<set>>
        + NomMunicipalite : string <<get>> <<set>>
        + Etat : string <<get>> <<set>>
        + Pays : string  <<get>> <<set>>
    }
}

package Application {
    ClientUIConsole "1" --> "1" IDepotClients

    class ClientUIConsole {
        - m_depotClient : IDepotClients
        + ctor(p_depotClient : IDepotClients)
        + AfficherMenu()
        + SaisirChoixMenu() : int
        + ExecuterUI()
        + SaisirClientAvecAdresse() : Client
        + AfficherClient(p_client: Client)
        + RechercherEtAfficherClientParId()
        + ListerEtAfficherClients()
        - GenererAdresseAleatoire() : Adresse
    }
}

package TraitementsLots {
    interface TraitementLot {
        + Executer()
    }
}

package TraitementsLots.ModifierNomPrenomPremiereLettreMajuscules {
    TraitementLot <|.. ModifierNomPrenomPremiereLettreMajusculesTraitementLot

    class ModifierNomPrenomPremiereLettreMajusculesTraitementLot {
        + Executer()
    }
}

package TraitementsLots.ModifierPaysMajusculesClients {
    TraitementLot <|.. ModifierPaysMajusculesClientsTraitementLot

    class ModifierPaysMajusculesClientsTraitementLot {
        + Executer()
    }
}

' TraitementsLots <.. TraitementsLots.ModifierNomPrenomPremiereLettreMajuscules
' TraitementsLots <.. TraitementsLots.ModifierPaysMajusculesClients

' Entites <.. CoucheAccesDonnees.JSON
' Entites <.. CoucheAccesDonnees.XML
' Entites <.. Application
' Entites <.. TraitementsLots

@enduml