@startuml DiagDTO

skinparam classAttributeIconSize 0
skinparam class {
    BackgroundColor White
    BorderColor #000
}

DessinXYZDTO --> "*" FormeXYZDTO
FormeXYZDTO <|-- CercleXYZDTO
FormeXYZDTO <|-- PolygoneXYZDTO
CercleXYZDTO --> "1" Point2DXYZDTO
PolygoneXYZDTO --> "3..n" Point2DXYZDTO

class Point2DXYZDTO {
    + X : int <<get>> <<set>>
    + Y : int <<get>> <<set>>
}

abstract FormeXYZDTO {
    
}

class CercleXYZDTO {
    + Rayon : int <<get>> <<set>>
    + Centre : Point2D<<get>> <<set>>
}

class PolygoneXYZDTO {
    + Sommets : List<Point2D> <<get>> <<set>>    
}

@enduml