@startuml Exception

Object <|-- Exception

Exception <|-- SystemException

SystemException <|-- IndexOutOfRangeException
SystemException <|-- NullReferenceException
SystemException <|-- InvalidOperationException

SystemException <|-- ArgumentException

class Exception {
    InnerException : Exception <<get>>
    Message : string <<get>>
    StackTrace : string <<get>>

    + Exception()
    + Exception(p_message : string)
    + Exception(p_message : string, p_innerException : Exception)

}

class ArgumentException {
    ParamName : string <<get>>

    + ArgumentException()
    + ArgumentException(p_message : string)
    + ArgumentException(p_message : string, p_innerException : Exception)
    + ArgumentException(p_message : string, p_nomParametre : string)
    + ArgumentException(p_message : string, p_nomParametre : string, p_innerException : Exception)

}

@enduml