@startuml DiagAppFactureGen

skinparam classAttributeIconSize 0
skinparam class {
    BackgroundColor White
    BorderColor #000
}

interface IDisposable {
    + Dispose()
}

interface IObservable<TypeEvenement> {
    + Subscribe(p_observateur : IObserver<TypeEvenement>) : IDisposable
}

interface IObserver<TypeEvenement> {
    + OnCompleted()
    + OnError(p_exception : Exception)
    + OnNext(p_valeur : TypeEvenement)
}

class FactureModel {
    - m_lignesFactureModel : List<LigneFactureModel>
    - m_observateurs : List<IObserver<FactureModelEvent>>
    + Total : decimal <<get>>
    + ctor()
    + Subscribe(p_observateur : IObserver<FactureModelEvent>) : IDisposable
    + AjouterLigneFactureModel(p_ligneFactureModel : LigneFactureModel)
    + Nouvelle()
}

class fEcranPrincipal {
    - m_FactureModel : FactureModel
    - m_ecranClient : fEcranClient
    + ctor()
    ...()
}

class fEcranClient {
    + ctor()
    ...()
}

class ObservateurFactureModel {
    - m_seDesabonner : IDisposable
    - m_action : Action<FactureModelEvent>
    + ctor(p_sujet : IObservable<FactureModelEvent>, p_action : Action<FactureModelEvent>)
    + OnCompleted()
    + OnError(p_exception : Exception)
    + OnNext(p_valeur : FactureModelEvent)
    + SeDesabonner()
}

class UnsubscriberFactureModel {
    - m_observer : IObserver<FactureModelEvent>
    - m_observers : List<IObserver<FactureModelEvent>>
    + ctor(p_observers : List<IObserver<FactureModelEvent>>, p_observer : IObserver<FactureModelEvent>)
    + Dispose()
}

class FactureModelEvent {
    + Type : FactureModelEventType <<get>> <<set>>
    + LigneFactureModel : LigneFactureModel <<get>> <<set>>
    + FactureModel : FactureModel <<get>> <<set>>
}

enum FactureModelEventType {
    AJOUT_LIGNE,
    NOUVELLE
}

FactureModelEvent "n" --> "1" FactureModel
FactureModelEvent "n" --> "1" LigneFactureModel
FactureModelEvent "n" --> "1" FactureModelEventType

fEcranPrincipal "1" -right-> "1" FactureModel : <<create>>
fEcranPrincipal "1" -left-> "1" fEcranClient
'fEcranPrincipal "1" ..> "1" ObservateurFactureModel : <<create>>

FactureModel "1" -left-> "n" IObserver
FactureModel "1" -right-> "n" LigneFactureModel

'fEcranClient "1" --> "1" FactureModel
'fEcranClient "1" ..> "1" ObservateurFactureModel : <<create>>

IObserver <|.. ObservateurFactureModel
IDisposable <|.. UnsubscriberFactureModel
IObserver <.. UnsubscriberFactureModel
IObservable <|.. FactureModel


@enduml
