@startuml DiagDTO

skinparam classAttributeIconSize 0
skinparam class {
    BackgroundColor White
    BorderColor #000
}

interface IDisposable {
    + Dispose()
}

interface IObservable<TypeEvenement> {
    + Subscribe(p_observateur : IObserver<TypeEvenement>) : IDisposable
}

interface IObserver<TypeEvenement> {
    + OnCompleted()
    + OnError(p_exception : Exception)
    + OnNext(p_valeur : TypeEvenement)
}

class SujetObservable {
    + Valeur : string <<get>> <<set>>
    - m_observateurs : List<IObserver<string>>
    - m_valeur : string
    + ctor()
    + Subscribe(p_observateur : IObserver<string>) : IDisposable
    - InformerObersateurValeurChangee()
}

class ObservateurXYZ {
    - m_seDesabonner : IDisposable
    + ctor(p_sujet : IObservable<string>)
    + OnCompleted()
    + OnError(p_exception : Exception)
    + OnNext(p_valeur : string)
    + SeDesabonner()
}

class UnsubscriberSujetObservable {
    - m_observer : IObserver<string>
    - m_observers : List<IObserver<string>>
    + UnsubscriberSujetObservable(p_observers : List<IObserver<string>>, p_observer : IObserver<string>)
    + Dispose()
}

SujetObservable "1" -right-> "n" IObserver : \t
IObserver <|.. ObservateurXYZ
IDisposable <|.. UnsubscriberSujetObservable
IObservable <|.. SujetObservable


@enduml
