@startuml DiagDTO

skinparam classAttributeIconSize 0
skinparam class {
    BackgroundColor White
    BorderColor #000
}

interface IDisposable {
    + Dispose()
}

interface IObservable<TypeAObserver> {
    + Subscribe(p_observateur : IObserver<TypeAObserver>) : IDisposable
}

interface IObserver<TypeAObserver> {
    + OnCompleted()
    + OnError(p_exception : Exception)
    + OnNext(p_valeur : TypeAObserver)
}

class SujetObservable {
    + Valeur : string <<get>> <<set>>
    - m_observateurs : List<IObserver<string>>
    - m_valeur : string
    + ctor()
    + Subscribe(p_observateur : IObserver<string>) : IDisposable
    - InformerObersateurValeurChangee()
}

class ObservateurXYZ {
    - m_seDesabonner : IDisposable
    + ctor(p_sujet : IObservable<string>)
    + OnCompleted()
    + OnError(p_exception : Exception)
    + OnNext(p_valeur : string
    + SeDesabonner()
}

class UnsubscribeSujetObservable {
    - m_observer : IObserver<TypeAObserver>
    - m_observers : List<IObserver<TypeAObserver>>
    + UnsubscribeSujetObservable(p_observers : List<IObserver<TypeAObserver>>, p_observer : IObserver<TypeAObserver>)
    + Dispose()
}

SujetObservable "1" -right-> "n" ObservateurXYZ
IObserver <|.. ObservateurXYZ
IDisposable <|.. UnsubscribeSujetObservable
IObservable <|.. SujetObservable


@enduml