@startuml diagDessin

namespace System.Drawing {
    class PointF {}
}

class ConfigurationRevolution {
    + PasAngle : int <<get>> <<set>>
    + LongueurDepart : int <<get>> <<set>>
    + NombreLignes : int <<get>> <<set>>
    + PasLonguer : int <<get>> <<set>>
    + PositionDepart : PointF <<get>> <<set>>
}
class DessinRevolution <<static>> {
    + {static} GenererPoints(p_configurationRevolution:ConfigurationRevolution) : List<PointF>
}
class fDessinLignes <<partial>> {
    + fDessinLignes()
    + EtablirConfiguration() : ConfigurationRevolution
    + Dessiner(p_configurationRevolution:ConfigurationRevolution, p_graphics:Graphics, p_pen:Pen) : void
}
Form <|-- fDessinLignes

class Program <<static>> {
    {static} Main() : void
}

Program .right.> fDessinLignes : <<create>>

@enduml
