@startuml OCP_V01_s01

skinparam classAttributeIconSize 0
skinparam class {
    BackgroundColor White
    BorderColor #000
}
allowmixing

interface ICalculInteret {
    + CalculerMontantInteretJournalier() : decimal
}

class CalculInteretFixe {
    + CalculerMontantInteretJournalier() : decimal
}

class CalculInteretVariable {
    + CalculerMontantInteretJournalier() : decimal
}

ICalculInteret <|.. CalculInteretFixe
ICalculInteret <|.. CalculInteretVariable

@enduml