@startuml LSP_v01

skinparam classAttributeIconSize 0
skinparam class {
    BackgroundColor White
    BorderColor #000
}
allowmixing
'skinparam linetype ortho

IFormeGeometriqueDessinable <|.. Rectangle
Rectangle <|-- Carre

interface IFormeGeometriqueDessinable {

}

class Rectangle {
    + Hauteur : float <<get>> <<set>>
    + Largeur : float <<get>> <<set>>
}

class Carre {
    + Hauteur : float <<get>> <<set>>
    + Largeur : float <<get>> <<set>>
}

@enduml